services:
  - type: web
    name: hardcopy
    env: ruby
    plan: starter
    buildCommand: bundle install && bundle exec rake assets:precompile && bundle exec rake assets:clean
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hardcopy-postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: hardcopy-postgres
    plan: starter
    databaseName: hardcopy_production